site_name: Prometheus FDW
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: light mode
nav:
  - Prometheus FDW: 'index.md'
  - hello world: 
    - 'hello_world/basic_setup.md'
  - practical example: 
    - 'practical_example/setup.md'
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- codehilite:
- admonition
- extra
- pymdownx.snippets:
    check_paths: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
plugins:
  - search
  - mkdocstrings